apiVersion: v1
kind: Secret

metadata:
  name: hostel-db-secret
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

type: Opaque

stringData:
  DATABASE_URL: "postgresql://hostel_demo_db_user:9V5DDMLVkxHDr6NQw7cN4FLGTWcQHq1J@dpg-d9a8jpho3t8c738fspbg-a.ohio-postgres.render.com/hostel_demo_db?sslmode=require"